[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers =
    ui: запускает все UI автотесты
    admin: автотесты для проверки админ панели
    smoke: смоук автотесты
    registration: автотесты на регистрацию
    regression: для регрессионных тестов
    courses: для тестов, связанных с курсами
    critical: критичные автотесты
    slow: медленные автотесты
    some: некоторые автотесты
    authorization: автотесты на авторизацию
    integration: интеграционные автотесты
    dashboard: маркировка для тестов, связанных с рабочей панелью.
