[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers =
    ui: запускает все UI автотесты
    smoke: смоук автотесты
    registration: автотесты на регистрацию
    regression: автотесты на регрессию
    critical: критичные автотесты
    slow: медленные автотесты
    some: некоторые автотесты
    authorization: автотесты на авторизацию

#python -m pytest -s -v -m "smoke"