[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers =
    registration: автотесты на регистрацию
    regression: для регрессионных тестов
    courses: для тестов, связанных с курсами
    authorization: автотесты на авторизацию
    dashboard: маркировка для тестов, связанных с рабочей панелью.
